### ISSUE TITLE
Can I get these mods

### ISSUE THREAD

**Issue by BaiNan-Y** [minecraftgive/DreadHungerMod#1]
Your mods are interesting, can I pay it ?
If can,how can I get these mods ?

**Comment by minecraftgive** [comment]
### All of them are FREE
and I'm not the creator of these mods.
This repo is just a storage place of some docs or files.
You can download some of them here https://minecraftgive-my.sharepoint.com/:f:/g/personal/minecraftgive_minecraftgive_onmicrosoft_com/EvYboYffauNGnQmm3UWsIDMBxu6oG2aENzcO1FlEJkqBtA?e=31nbZw

### What about the other?
The creators(The Septenary Gods team) didn't publish them

## What can you do
If you want to try those mods, one way is to join dc server or qq group(see below),use bots to create servers with those mods(free for everyone,we accept donations). Another is visit a website to create servers.


### links
The website
https://moeyy.cn/dreadhunger

Unofficial Dread Hunger Server
https://discord.com/invite/gMKUF9HDZA

Moeyy's DH server
https://discord.com/invite/f24JgpH8JE

QQ group
624995738

**Comment by BaiNan-Y** [comment]
Thank u very much, I've been looking for these for a while, it helps me a lot :star: :star: :star: :star:
